### PR TITLE
Updating Parameter Sweep to Include Results for GTEx and TARGET

### PR DESCRIPTION
**Pull request by gwaygenomics**
This pull request updates nearly everything in the `1.initial-z-sweep` module. Many new figures and results are added, but it is not much different than the previous version. The specific updates include:

| Change | Commit | Priority |
| :---------: | :--------: | :-----: |
| Adding new and removing old individual sweep files | 0161fd7 and b1e52a0 | NA |
| Adding new and removing old text based results | 63a02ed and 9c49638 | NA |
| Adding new and removing old figures | 27bc82a and 4404140 | NA |
| Replacing old script (`.R` file) with a jupyter notebook with R kernel | 002ee07 and a4f100f (also see 9715f2a)  | 1 |
| Updating README for new datasets and new results | f304307 | 2 |
| Adding helper scripts to summarize results and help with plotting | 583e6f6 and 89d201f | 3 |

The main update is the addition of the notebook (002ee07), which outlines the updated analysis (including adding GTex and TARGET) and all updated results. Thanks!

### CODE REVIEW

**Comment by danich1** [comment]
This is pretty huge. I can't even jump to the scripts that need to be reviewed. Can we break the PR down into multiple PRs where github won't yell at me?

**Comment by danich1** [comment]
The code LGTM, but would like to see what @jaclyn-taroni has to say on it.

**Comment by jaclyn-taroni** [comment]
Alright, I am taking a look. Since I'm looking at individual commits, there will be a series of single comments and for that I apologize in advance!

**Comment by jaclyn-taroni** [comment]
Having some trouble with the UI -- consider this approved!

**Pull request merged**
